cpingfolder/urls.py
from django.contrib import admin
from django.urls import path
from cping23 import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tabla-posiciones/', views.tabla_posiciones, name='tabla_posiciones'),
    path('partidos/', views.mostrar_partidos, name='partidos'),
    path('partidos/<int:pk>/', views.resumen, name='resumen'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cping23/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver

class Equipo(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.nombre

class Partido(models.Model):
    DEPORTE_CHOICES = (
        ('FUTBOL_MASCULINO', 'Fútbol Masculino'),
        ('FUTBOL_FEMENINO', 'Fútbol Femenino'),
        ('BASKET_MASCULINO', 'Básquet Masculino'),
        ('BASKET_FEMENINO', 'Básquet Femenino'),
        ('VOLLEY_MASCULINO', 'Vóley Masculino'),
        ('VOLLEY_FEMENINO', 'Vóley Femenino'),
        ('PIKI', 'Piki'),
        ('FIFA23', 'FIFA 23'),
        ('PING_PONG', 'Ping Pong'),
        ('POKER', 'Poker'),
        ('AJEDREZ', 'Ajedrez'),
        ('TRUCO', 'Truco'),
    )

    equipo_local = models.ForeignKey(Equipo, on_delete=models.CASCADE, related_name='partidos_local')
    equipo_visitante = models.ForeignKey(Equipo, on_delete=models.CASCADE, related_name='partidos_visitante')
    goles_local = models.PositiveIntegerField(blank=True, null=True)
    goles_visitante = models.PositiveIntegerField(blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    partido_numero = models.CharField(max_length=100, blank=True, null=True)
    fase_partido = models.CharField(max_length=99, blank=True, null=True)
    deporte = models.CharField(max_length=50, choices=DEPORTE_CHOICES, blank=True, null=True)

    def __str__(self):
        return f"Partido {self.id} {self.equipo_local} vs {self.equipo_visitante}"

    def get_absolute_url(self):
        return reverse('resumen', kwargs={'pk': self.pk})


class EventoPartido(models.Model):
    PARTIDO_EVENT_CHOICES = (
        ('INICIO DEL PARTIDO', 'Inicio del partido'),
        ('FINAL DEL PARTIDO', 'Fin del partido'),
    )

    partido = models.ForeignKey(Partido, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=100, choices=PARTIDO_EVENT_CHOICES)
    minuto = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.tipo} en el minuto {self.minuto} del partido {self.partido}"


class Evento(models.Model):
    PARTIDO_EVENT_CHOICES = (
        ('GOOOOL', 'Gol local'),
        ('GOOOL', 'Gol visitante'),
        ('TARJETA ROJA', 'Tarjeta roja local'),
        ('TARJETA ROJA ', 'Tarjeta roja visitante'),
        ('TARJETA AMARILLA', 'Tarjeta amarilla local'),
        ('TARJETA AMARILLA ', 'Tarjeta amarilla visitante'),
    )

    partido = models.ForeignKey(Partido, on_delete=models.CASCADE)
    minuto = models.PositiveIntegerField()
    tipo = models.CharField(max_length=100, choices=PARTIDO_EVENT_CHOICES)
    jugadores = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.tipo} en el minuto {self.minuto} del partido {self.partido}"


class TablaPosiciones(models.Model):
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    puntos = models.PositiveIntegerField(default=0)
    partidos_jugados = models.PositiveIntegerField(default=0)
    partidos_ganados = models.PositiveIntegerField(default=0)
    partidos_empatados = models.PositiveIntegerField(default=0)
    partidos_perdidos = models.PositiveIntegerField(default=0)
    goles_favor = models.PositiveIntegerField(default=0)
    goles_contra = models.PositiveIntegerField(default=0)
    diferencia_goles = models.IntegerField(default=0)

    @staticmethod
    def calcular_posiciones():
        equipos = Equipo.objects.all()
        TablaPosiciones.objects.all().delete()

        for equipo in equipos:
            partidos_local = Partido.objects.filter(equipo_local=equipo)
            partidos_visitante = Partido.objects.filter(equipo_visitante=equipo)
            partidos_jugados = partidos_local.count() + partidos_visitante.count()

            partidos_ganados = partidos_local.filter(goles_local__gt=models.F('goles_visitante')).count()
            partidos_ganados += partidos_visitante.filter(goles_visitante__gt=models.F('goles_local')).count()

            partidos_empatados = partidos_local.filter(goles_local=models.F('goles_visitante')).count()
            partidos_empatados += partidos_visitante.filter(goles_visitante=models.F('goles_local')).count()

            partidos_perdidos = partidos_jugados - partidos_ganados - partidos_empatados

            goles_favor = partidos_local.aggregate(total=models.Sum('goles_local'))['total'] or 0
            goles_favor += partidos_visitante.aggregate(total=models.Sum('goles_visitante'))['total'] or 0

            goles_contra = partidos_local.aggregate(total=models.Sum('goles_visitante'))['total'] or 0
            goles_contra += partidos_visitante.aggregate(total=models.Sum('goles_local'))['total'] or 0

            puntos = partidos_ganados * 3 + partidos_empatados

            diferencia_goles = goles_favor - goles_contra

            TablaPosiciones.objects.create(
                equipo=equipo,
                puntos=puntos,
                partidos_jugados=partidos_jugados,
                partidos_ganados=partidos_ganados,
                partidos_empatados=partidos_empatados,
                partidos_perdidos=partidos_perdidos,
                goles_favor=goles_favor,
                goles_contra=goles_contra,
                diferencia_goles=diferencia_goles
            )

@receiver(post_save, sender=Partido)
def actualizar_tabla_posiciones(sender, instance, **kwargs):
    TablaPosiciones.calcular_posiciones()

cping23/views.py
from django.shortcuts import render, get_object_or_404
from .models import Equipo, TablaPosiciones, Partido, Evento, EventoPartido

def tabla_posiciones(request):
    TablaPosiciones.calcular_posiciones()
    posiciones = TablaPosiciones.objects.order_by('-puntos', '-goles_favor')

    context = {
        'posiciones': posiciones
    }

    return render(request, 'tabla_posiciones.html', context)



def mostrar_partidos(request):
    deporte = request.GET.get('deporte', 'FUTBOL_MASCULINO')  # Valor por defecto: Fútbol Masculino
    partidos = Partido.objects.filter(deporte=deporte)
    return render(request, 'partidos.html', {'partidos': partidos})

def resumen(request, pk):
    partido = get_object_or_404(Partido, pk=pk)
    partidos = Partido.objects.all()
    eventos_partido = EventoPartido.objects.filter(partido=partido)
    eventos = Evento.objects.filter(partido=partido)

    context = {
        'partido': partido,
        'partidos': partidos,
        'eventos_partido': eventos_partido,
        'eventos': eventos
    }

    return render(request, 'resumen.html', context)

templates/cabecera.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Centro de Estudiantes-FCyT</title>
	<meta charset="UTF-8">
	<meta name="description" content="Centro de Estudiantes FCyT-UNCA">
	<meta name="keywords" content="event, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Favicon -->
	<link href="{% static "image/favicon.png" %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}"/>
	<link rel="stylesheet" href="{% static "css/themify-icons.css" %}"/>
	<link rel="stylesheet" href="{% static "css/magnific-popup.css" %}"/>
	<link rel="stylesheet" href="{% static "css/animate.css" %}"/>
	<link rel="stylesheet" href="{% static "css/owl.carousel.css" %}"/>
	<link rel="stylesheet" href="{% static "css/style.css" %}"/>
    <link rel="stylesheet" href="{% static "css/backtop.css" %}"/>
    <link rel="stylesheet" href="{% static "css/contviews.css" %}"/>
    <link rel="stylesheet" href="{% static "bootstrap-icons/bootstrap-icons.scss" %}"/>
    <link rel="manifest" href="/manifest.json">


    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="//cdn-images.mailchimp.com/embedcode/classic-071822.css" rel="stylesheet" type="text/css">



    <!-- Back to top button -->
    <a id="button"></a>

	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

    <style>
        .sombra{
            margin:10px;
            box-shadow: 10px 10px 5px grey;
        }
    </style>


</head>
<body>
{% include "nav.html" %}

templates/headercping.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Centro de Estudiantes-FCyT</title>
	<meta charset="UTF-8">
	<meta name="description" content="Centro de Estudiantes FCyT-UNCA">
	<meta name="keywords" content="event, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Favicon -->
	<link href="{% static "image/favicon.png" %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}"/>
	<link rel="stylesheet" href="{% static "css/themify-icons.css" %}"/>
	<link rel="stylesheet" href="{% static "css/magnific-popup.css" %}"/>
	<link rel="stylesheet" href="{% static "css/animate.css" %}"/>
	<link rel="stylesheet" href="{% static "css/owl.carousel.css" %}"/>
	<link rel="stylesheet" href="{% static "css/style.css" %}"/>
    <link rel="stylesheet" href="{% static "css/backtop.css" %}"/>
    <link rel="stylesheet" href="{% static "css/contviews.css" %}"/>
    <link rel="stylesheet" href="{% static "bootstrap-icons/bootstrap-icons.scss" %}"/>
    <link rel="manifest" href="/manifest.json">


    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="//cdn-images.mailchimp.com/embedcode/classic-071822.css" rel="stylesheet" type="text/css">



    <!-- Back to top button -->
    <a id="button"></a>

	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

    <style>
        .sombra{
            margin:10px;
            box-shadow: 10px 10px 5px grey;
        }
    </style>


</head>
<body>
{% include "navcping.html" %}

templates/partidos.html
{% include "headercping.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cupingcss/stylecup.css' %}">

    <style>
        /* Estilos para agregar espacio entre partidos */
        .partido-container {
            margin-bottom: 20px;
        }

        /* Estilos para resaltar los partidos */
        .partido {
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .partido:hover {
            background-color: #e5e5e5;
        }

        .hidden {
          display: none;
        }
    </style>
</head>
<body>

    <!-- Breadcrumb section -->
    <div class="site-breadcrumb"></div>
    <!-- Breadcrumb section end -->
    <div class="container">
        <ol class="breadcrumb" style="background-color: transparent; ">
            <li class="breadcrumb-item">
                <a href="/" style="color: black">
                    <i class="fa fa-home" style="color: black"></i> Inicio
                </a>
            </li>
            <li class="breadcrumb-item active">Resultados</li>
        </ol>
    </div>

    <!-- Código Nuevo -->
    <section class="full-courses-section spad pt-0">
        <h3 class="h3-stylecup">RESULTADOS DE LA COPA INGE 2023</h3>

        <div style="text-align: center;">
            <form method="get">
                <label for="deporte">Selecciona un deporte:</label>
                <select id="deporte" name="deporte" style="border-radius: 5px; padding: 8px; ">
                    <option style="padding-bottom: 5px;" value="FUTBOL_MASCULINO">Fútbol Masculino</option>
                    <option value="FUTBOL_FEMENINO">Fútbol Femenino</option>
                    <option value="BASKET_MASCULINO">Basketball Masculino</option>
                    <option value="BASKET_FEMENINO">Basketball Femenino</option>
                    <option value="FIFA23">FIFA23</option>
                    <!-- Agrega las opciones para los demás deportes -->
                </select>&nbsp;&nbsp;&nbsp;
                <button type="submit" style="border-radius: 8px; background-color: #808080; color: white; padding: 8px; box-shadow: none; border: none;">Mostrar resultados</button>
            </form>
        </div><br>

        <div class="containerp">


            <!-- code here -->
            <div class="match">
                <div class="match-header">
                    <div class="match-status">En Vivo</div>
                    <div class="match-tournament">
                        <img class="img-stylecup" src="{% static 'image/Logo copa inge png.png' %}" />Copa Inge 2023
                    </div>
                    <div class="match-actions">
                        <button class="btn-icon"><i class="material-icons-outlined">10</i></button>
                        <button class="btn-icon"><i class="material-icons-outlined">/</i></button>
                        <button class="btn-icon"><i class="material-icons-outlined">06</i></button>
                        <button class="btn-icon"><i class="material-icons-outlined">/</i></button>
                        <button class="btn-icon"><i class="material-icons-outlined">2023</i></button>
                    </div>
                </div>

                {% for partido in partidos %}

                <div class="match-content">
                    <div class="column">
                        <div class="team team--home">
                            <div class="team-logo">
                                {% if partido.equipo_local.imagen %}
                                <img src="{{ partido.equipo_local.imagen.url }}" alt="" class="img-stylecup equipo-img">
                                {% endif %}
                            </div>
                            <h2 class="team-name">{{ partido.equipo_local.nombre }}</h2>
                            <div class="match-time-lapsed">
                                {% for evento in partido.evento_set.all %}
                                {% if evento.tipo == 'GOOOOL' %}
                                <i class="fa fa-soccer-ball-o"></i> {{ evento.jugadores }} {{ evento.minuto }}'  <br>
                                {% endif %}
                                {% if evento.tipo == 'TARJETA ROJA' %}
                                <i class="fas fa-square redcard-icon"></i> {{ evento.jugadores }} {{ evento.minuto }}'  <br>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="column-match-details">
                        <div class="match-details">
                            <div class="match-date">
                                <strong>{{ partido.fecha }}</strong>
                            </div>
                            <div class="match-score">

                                <span class="match-score-number">{{ partido.goles_local }}</span>
                                <span class="match-score-divider">:</span>
                                <span class="match-score-number">{{ partido.goles_visitante }}</span>

                            </div>
                            <div class="match-referee">
                                {{ partido.partido_numero }}: <strong>{{ partido.fase_partido }}</strong>
                            </div>
                            <!--<div class="match-bet-options">
                                <button class="match-bet-option">1.48</button>
                                <button class="match-bet-option">4.98</button>
                                <button class="match-bet-option">8.24</button>
                            </div>-->
                            <button class="match-bet-place"><a style="color: white" href="{% url 'resumen' pk=partido.pk %}">RESUMEN</a></button>
                        </div>
                    </div>
                    <div class="column">
                        <div class="team team--away">
                            <div class="team-logo">
                                {% if partido.equipo_visitante.imagen %}
                                <img src="{{ partido.equipo_visitante.imagen.url }}" alt="" class="img-stylecup equipo-img">
                                {% endif %}
                            </div>
                            <h2 class="team-name">{{ partido.equipo_visitante.nombre }}</h2>
                            <div class="match-time-lapsed">
                                {% for evento in partido.evento_set.all %}
                                {% if evento.tipo == 'GOOOL' %}
                                <i class="fa fa-soccer-ball-o"></i> {{ evento.jugadores }} {{ evento.minuto }}'  <br>
                                {% endif %}
                                {% if evento.tipo == 'TARJETA ROJA ' %}
                                <i class="fas fa-square redcard-icon"></i> {{ evento.jugadores }} {{ evento.minuto }}'  <br>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <br><br>

                {% endfor %}
            </div>

        </div>

    </section>

    {% include "pie_pagina.html" %}
    <script src="{% static 'js/cupingjs/script.js' %}"></script>
</body>
</html>

templates/resumen.html
{% include "headercping.html" %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Resultados</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cupingcss/stylecup.css' %}">

    <style>
        /* Estilos para agregar espacio entre partidos */
        .partido-container {
            margin-bottom: 20px;
        }

        /* Estilos para resaltar los partidos */
        .partido {
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .partido:hover {
            background-color: #e5e5e5;
        }
    </style>
</head>
<body>

    <!-- Breadcrumb section -->
    <div class="site-breadcrumb">

    </div>
    <!-- Breadcrumb section end -->
    <div class="container">
    <ol class="breadcrumb" style="background-color: transparent;">
      <li class="breadcrumb-item" ><a href="/" style="color: black"><i class="fa fa-home" style="color: black"></i> Inicio</a></li>
        <li class="breadcrumb-item "><a href="/partidos" style="color: black">Resultados</a></li>
      <li class="breadcrumb-item active">Resumen</li>
    </ol>
    </div>

    <!--Código Nuevo-->
    <section class="full-courses-section spad pt-0">
        <h3 class="h3-stylecup">RESUMEN DEL PARTIDO</h3>
         <div class="containerp">
        <!-- code here -->
        <div class="match">
            <div class="match-header">

                <div class="match-tournament"><img class="img-stylecup" src="{% static "image/Logo copa inge png.png" %}" />Copa Inge 2023</div>
                <div class="match-actions">
                    <button class="btn-icon"><i class="material-icons-outlined">10</i></button>
                    <button class="btn-icon"><i class="material-icons-outlined">/</i></button>
                    <button class="btn-icon"><i class="material-icons-outlined">06</i></button>
                    <button class="btn-icon"><i class="material-icons-outlined">/</i></button>
                    <button class="btn-icon"><i class="material-icons-outlined">2023</i></button>
                </div>
            </div>


            <div class="match-content">

                <div class="column">
                    <div class="team team--home">
                        <div class="team-logo">
                            {% if partido.equipo_local.imagen %}
                                    <img  src="{{ partido.equipo_local.imagen.url }}" alt="" class="img-stylecup equipo-img">
                            {% endif %}
                        </div>
                        <h2 class="team-name">{{ partido.equipo_local.nombre }}</h2>

                    </div>
                </div>
                <div class="column">
                    <div class="match-details">
                        <div class="match-date">
                            <strong>{{ partido.fecha }}</strong>
                        </div>
                        <div class="match-score">
                            <span class="match-score-number ">{{ partido.goles_local }}</span>
                            <span class="match-score-divider">:</span>
                            <span class="match-score-number">{{ partido.goles_visitante }}</span>
                        </div>
                        <div class="match-referee">
                            {{ partido.partido_numero }}: <strong>{{ partido.fase_partido }}</strong>
                        </div>
                        <!--<div class="match-bet-options">
                            <button class="match-bet-option">1.48</button>
                            <button class="match-bet-option">4.98</button>
                            <button class="match-bet-option">8.24</button>
                        </div>-->
                        <!--<button class="match-bet-place">RESUMEN</button>-->
                    </div>
                </div>
                <div class="column">
                    <div class="team team--away">
                        <div class="team-logo">
                            {% if partido.equipo_visitante.imagen %}
                                    <img src="{{ partido.equipo_visitante.imagen.url }}" alt="" class="img-stylecup equipo-img">
                            {% endif %}
                        </div>
                        <h2 class="team-name">{{ partido.equipo_visitante.nombre }}</h2>


                    </div>
                </div>
            </div>

             {% for eventopartido in partido.eventopartido_set.all %}
            {% if eventopartido.tipo == 'INICIO DEL PARTIDO' %}
                <div class="match-header" style="padding: 0px;"></div>
                <div class="match-header">
                    <div class="match-time-lapsed">
                        <i class="fa fa-clock-o"></i><span> {{ eventopartido.tipo }}</span>
                    </div>
                    <div class="match-actions">
                        <button class="btn-icon"><i class="material-icons-outlined">{{ eventopartido.minuto }}'</i></button>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

            {% for evento in partido.evento_set.all %}
                <div class="match-header" style="padding: 0px;"></div>
                <div class="match-header">
                    <div class="match-time-lapsed">
                        {% if evento.tipo == 'GOOOOL' or evento.tipo == 'GOOOL' %}
                            <i class="fa fa-soccer-ball-o"></i><span> {{ evento.tipo }}</span>
                        {% elif evento.tipo == 'TARJETA ROJA' or evento.tipo == 'TARJETA ROJA ' %}
                            <i class="fas fa-square redcard-icon"></i><span> {{ evento.tipo }}</span>
                        {% elif evento.tipo == 'TARJETA AMARILLA' or evento.tipo == 'TARJETA AMARILLA ' %}
                            <i class="fas fa-square yellowcard-icon"></i><span> {{ evento.tipo }}</span>
                        {% endif %}
                    </div>

                    <div class="match-actions">
                        <button class="btn-icon"><i class="material-icons-outlined">{{ evento.minuto }}'</i></button>
                    </div>
                </div>

                <div class="match-content">
                    <div class="column-resumen">
                        <div class="match-referee-resumen">
                            <strong>{{ evento.jugadores }}</strong>
                        </div>
                        <div class="match-referee-resumen">
                            {% if evento.tipo == 'GOOOOL' or evento.tipo == 'TARJETA ROJA' or evento.tipo == 'TARJETA AMARILLA' %}
                                <span>&nbsp;&nbsp; {{ partido.equipo_local.nombre }} </span>
                            {% elif evento.tipo == 'GOOOL' or evento.tipo == 'TARJETA ROJA ' or evento.tipo == 'TARJETA AMARILLA ' %}
                                <span>&nbsp;&nbsp; {{ partido.equipo_visitante.nombre }} </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="column-resumen">
                        <div class="team team--away">
                            <div>
                                {% if evento.tipo == 'GOOOOL' or evento.tipo == 'TARJETA ROJA' or evento.tipo == 'TARJETA AMARILLA' %}
                                    {% if partido.equipo_local.imagen %}
                                        <img src="{{ partido.equipo_local.imagen.url }}" alt="" class="equipo-img">
                                    {% endif %}
                                {% elif evento.tipo == 'GOOOL' or evento.tipo == 'TARJETA ROJA ' or evento.tipo == 'TARJETA AMARILLA ' %}
                                    {% if partido.equipo_visitante.imagen %}
                                        <img src="{{ partido.equipo_visitante.imagen.url }}" alt="" class="equipo-img">
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
         {% for eventopartido in partido.eventopartido_set.all %}
            {% if eventopartido.tipo == 'FINAL DEL PARTIDO' %}
                <div class="match-header" style="padding: 0px;"></div>
                <div class="match-header">
                    <div class="match-time-lapsed">
                        <i class="fa fa-clock-o"></i><span> {{ eventopartido.tipo }}</span>
                    </div>
                    <div class="match-actions">
                        <button class="btn-icon"><i class="material-icons-outlined">{{ eventopartido.minuto }}'</i></button>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        </div>
    </div>
    </section>

{% include "pie_pagina.html" %}
    <script src="{% static 'js/cupingjs/script.js' %}"></script>
</body>
</html>